name: "publish json"
on:
  push:
    branches:
      - "*"

jobs:
  compile:
    runs-on: self-hosted
    environment: 
      name: UIPATH
    steps:
      - name: setup python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.10' 
        
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/windows@v2
        if: always()
        with:
          files: |
            "C:\Users\Docker\AppData\Local\Temp\test_result.json"
