name: "gen report"
on:
  push:
    branches:
      - "*"

jobs:
  compile:
    runs-on: windows-latest
    environment: 
      name: UIPATH
    steps:        
    - uses: actions/download-artifact@v4
      with:
       name: uipath_test_result
       path: ${{ github.workspace }}\result\

    - name: "show result"
      run: type ${{ github.workspace }}\result\test-summary.md
