name: "Deploy UiPath Package"
on:
  push:
    branches:
      - "*"

jobs:
  compile:
    runs-on: windows-latest
    env: 
      PROJECK_NAME: ""
      PACKAGE_VERSION: ""
    environment: 
      name: UIPATH
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup UiPath (uipcli) command line tool
        uses: Mikael-RnD/setup-uipath@v1

      - name: Pack UiPath project
        run: |
          foreach($package in Get-ChildItem -Path ${{ github.workspace }} -Recurse -Filter project.json -File) {
            $json = Get-Content "$package" | Out-String | ConvertFrom-Json
            $foo = $json.projectVersion
            $Name=$json.name
            Write-Output "PATH=$($package)" >> $Env:GITHUB_OUTPUT
            echo $foo
            $v= [version] "$foo"
            $newversion= "{0}.{1}.{2}.{3}" -f $v.Major, $v.Minor, ($v.Build),"${{github.run_number}}"
            $VERSION=[string]$newversion
            echo $VERSION
            echo $Name
            echo ${{ github.workspace }}\$Name.$VERSION.nupkg
            # Build and Deploy the Package
            uipcli package pack "$package" -o "${{ github.workspace }}\output" -v $VERSION -l en-US
            dir "${{ github.workspace }}\output"
            $env:PACKAGE_VERSION = $VERSION
            $env:PROJECK_NAME = $Name
            uipcli package deploy "${{ github.workspace }}\output\$($Name).$VERSION.nupkg" "https://cloud.uipath.com" DefaultTenant -t "${{secrets.UIPATH_USER_KEY}}" -a "${{secrets.UIPATH_ORGANIZATION_ID}}" -o docker_test
          }
          
      - name: Run UiPath Test
        run: uipcli test run "https://cloud.uipath.com" DefaultTenant -t "${{secrets.UIPATH_USER_KEY}}" -a "${{secrets.UIPATH_ORGANIZATION_ID}}" -o docker_test -r"${{ github.workspace }}\result\test_result.json" -s testset1
        continue-on-error: true
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}\result\
      - name: List env
        run: env
      - name: Upload Test Result
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PROJECK_NAME }}_${{ env.PACKAGE_VERSION }}_test_result
          path: ${{ github.workspace }}\result\test_result.json
          retention-days: 5
